bootstrap: 100
experimental_variables:
  k:
  - 1.0
  - 2.0
  - 3.0
  - 4.0
  - 0.1
  - 0.25
  - 0.3333333333333333
  - 0.5
  prevalence_disparity:
  - 0.25
  - 0.3333333333333333
  - 0.5
  - 1.0
  target_prevalence:
  - 0.25
  testing_disparity:
  - 0.25
  - 0.3333333333333333
  - 0.5
  - 1.0
  - 2.0
  - 3.0
  - 4.0
model_hparams:
  shared:
    epochs: 1000
    lr: 0.001
    optimizer: Adam
    weight_decay: 0.0
models:
- YModel
n: 10000
n_cpus: 0
name: sweep_20230704_v6_phase45
other_sim_kwargs:
  label_decision_fn0:
    kwargs:
      period: 0.5
      translate: 45
    name: SpinnySinewave
  label_decision_fn1:
    kwargs:
      period: 0.5
      translate: 45
    name: SpinnySinewave
  label_hardness_0: 10
  label_hardness_1: 10
  max_value: 1000.0
  min_value: -1000.0
  test_decision_fn0:
    kwargs:
      m: 1.0
    name: Linear
  test_decision_fn1:
    kwargs:
      m: 1.0
    name: Linear
