name: sweep_20230704_v6
n: 10000
n_cpus: 8
bootstrap: 100
experimental_variables:
    target_prevalence:
        - 0.25 
    testing_disparity:
        - 0.25
        - 0.3333333333333333
        - 0.5
        - 1.
        - 2.
        - 3.
        - 4.
    prevalence_disparity:
        - 0.25
        - 0.3333333333333333
        - 0.5
        - 1.
    k:
        - 0.1
        - 0.25 
        - 0.3333333333333333
        - 0.5
        - 1.
        - 2.
        - 3.
        - 4.
models:
    - "SELFModel"
other_sim_kwargs:
    min_value: -1000.
    max_value: 1000.
    label_hardness_0: 10
    label_hardness_1: 10
    test_decision_fn0:
        name: "Linear"
        kwargs:
            m: 1.
    test_decision_fn1:
        name: "Linear"
        kwargs:
            m: 1.
    label_decision_fn0:
        name: "SpinnySinewave"
        kwargs:
            period: 0.5
    label_decision_fn1:
        name: "SpinnySinewave"
        kwargs:
            period: 0.5
model_hparams:
    shared:
        optimizer: "Adam"
        lr: 1.0e-3
        epochs: 1000
        weight_decay: 0.
    SELFModel:
        optimizer: "SGD"
        weight_decay: 2.0e-4
        optim_kwargs:
            nesterov: True
            momentum: 0.9
        lr: 0.01
        max_iters: 50
        self_patience: 1
        mean_teacher_alpha: 0.9
        alpha: 0.9
        noise_var: 0.05
        reg: 1.
        no_filter_positives: True 

