name: rebuttal_20231102_t0.1
n: 10000
n_cpus: 0
bootstrap: 100
experimental_variables:
    target_prevalence:
        - 0.25 
    testing_disparity:
        - 2.
    prevalence_disparity:
        - 0.5
    k:
        - 1.
models:
    - "DCEMModel"
other_sim_kwargs:
    min_value: -1000.
    max_value: 1000.
    label_hardness_0: 10
    label_hardness_1: 10
    test_decision_fn0:
        name: "Linear"
        kwargs:
            m: 1.
    test_decision_fn1:
        name: "Linear"
        kwargs:
            m: 1.
    label_decision_fn0:
        name: "SpinnySinewave"
        kwargs:
            period: 0.5
    label_decision_fn1:
        name: "SpinnySinewave"
        kwargs:
            period: 0.5
model_hparams:
    shared:
        optimizer: "Adam"
        lr: 1.0e-3
        epochs: 1000
        weight_decay: 0.
    DCEMModel:
        softmax_temperature: 0.1
        propensity_lr: 1.0e-3
        em_its: 50
        em_patience: 3
        m_step_warm_start: True
