bootstrap: 100
experimental_variables:
  k:
  - 1.0
  - 2.0
  - 4.0
  - 0.5
  prevalence_disparity:
  - 0.5
  - 1.0
  target_prevalence:
  - 0.25
  testing_disparity:
  - 2.0
  - 1.0
  - 0.5
model_hparams:
  DCEMModel:
    em_its: 50
    em_patience: 3
    initialize_tested_only: true
    m_step_warm_start: true
    propensity_lr: 0.001
    softmax_temperature: 0.1
  shared:
    epochs: 1000
    lr: 0.001
    optimizer: Adam
    weight_decay: 0.0
models:
- DCEMModel
n: 10000
n_cpus: 0
name: 20231215_t0.1_testedonly_phase330
other_sim_kwargs:
  label_decision_fn0:
    kwargs:
      period: 0.5
      translate: 330
    name: SpinnySinewave
  label_decision_fn1:
    kwargs:
      period: 0.5
      translate: 330
    name: SpinnySinewave
  label_hardness_0: 10
  label_hardness_1: 10
  max_value: 1000.0
  min_value: -1000.0
  test_decision_fn0:
    kwargs:
      m: 1.0
    name: Linear
  test_decision_fn1:
    kwargs:
      m: 1.0
    name: Linear
