name: group_testedonly_20240321
n: 10000
n_cpus: 0
bootstrap: 0
experimental_variables:
    target_prevalence:
        - 0.25 
    testing_disparity:
        - 3.
        - 2.
        - 1.
        - 0.5
        - 0.3333333333333333
    prevalence_disparity:
        - 0.5
        - 1.
    k:
        - 1.
        - 2.
        - 3.
        - 0.3333333333333333
        - 0.5
models:
    - "GroupDependentTestedOnlyModel"
other_sim_kwargs:
    min_value: -1000.
    max_value: 1000.
    label_hardness_0: 10
    label_hardness_1: 10
    test_decision_fn0:
        name: "Linear"
        kwargs:
            m: 1.
    test_decision_fn1:
        name: "Linear"
        kwargs:
            m: 1.
    label_decision_fn0:
        name: "SpinnySinewave"
        kwargs:
            period: 0.5
    label_decision_fn1:
        name: "SpinnySinewave"
        kwargs:
            period: 0.5
model_hparams:
    shared:
        optimizer: "Adam"
        lr: 1.0e-3
        epochs: 1000
        weight_decay: 0.
