bootstrap: 100
experimental_variables:
  k:
  - 0.25
  - 0.3333333333333333
  - 0.5
  - 1
  - 2
  - 3
  - 4
  - 5
  - 10.0
  testing_disparity:
  - 0.5
  - 0.6666666666666667
  - 1
  - 1.5
  - 2
model_hparams:
  SAREMModel:
    em_its: 50
    em_patience: 3
    m_step_warm_start: true
    propensity_lr: 0.001
    y_prior_eps: 1.0e-06
  shared:
    epochs: 10000
    hidden_sizes:
    - 128
    - 128
    - 16
    lr: 1.0e-05
    optimizer: Adam
    weight_decay: 0.001
models:
- SAREMModel
n_cpus: 0
name: sepsis_20230724_alpha0.000
other_sim_kwargs:
  data_path: /data2/username/sepsis3_mimic_ros_replication.csv
  label_col: sepsis-3
  test_decision_fn0:
    kwargs:
      weights:
      - 0.0
      - 1.0
    name: NaiveLinearSepsisBoundary
  test_decision_fn1:
    kwargs:
      weights:
      - 0.0
      - 1.0
    name: NaiveLinearSepsisBoundary
