bootstrap: 100
experimental_variables:
  k:
  - 0.25
  - 0.3333333333333333
  - 0.5
  - 1
  - 2
  - 3
  - 4
  - 5
  - 10.0
  testing_disparity:
  - 0.5
  - 0.6666666666666667
  - 1
  - 1.5
  - 2
model_hparams:
  shared:
    epochs: 10000
    hidden_sizes:
    - 128
    - 128
    - 16
    lr: 1.0e-05
    optimizer: Adam
    weight_decay: 0.001
models:
- YObsModel
n_cpus: 0
name: sepsis_20230724_alpha0.300
other_sim_kwargs:
  data_path: /data2/username/sepsis3_mimic_ros_replication.csv
  label_col: sepsis-3
  test_decision_fn0:
    kwargs:
      weights:
      - 0.30000000000000004
      - 0.7
    name: NaiveLinearSepsisBoundary
  test_decision_fn1:
    kwargs:
      weights:
      - 0.30000000000000004
      - 0.7
    name: NaiveLinearSepsisBoundary
